"""audit-check

Revision ID: 6dbe323b9017
Revises: c4714aaaa904
Create Date: 2025-09-15 05:23:22.416077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6dbe323b9017'
down_revision: Union[str, Sequence[str], None] = 'c4714aaaa904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adminuser_email'), table_name='adminuser')
    op.drop_table('adminuser')
    op.drop_index(op.f('ix_ticket_event_scanned_by'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_event_used'), table_name='ticket')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ticket_event_used'), 'ticket', ['event', 'used'], unique=False)
    op.create_index(op.f('ix_ticket_event_scanned_by'), 'ticket', ['event', 'scanned_by'], unique=False)
    op.create_table('adminuser',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('ADMIN', 'SUBADMIN', 'EDITOR', 'SCANNER', name='adminrole'), autoincrement=False, nullable=False),
    sa.Column('token_version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('adminuser_pkey'))
    )
    op.create_index(op.f('ix_adminuser_email'), 'adminuser', ['email'], unique=True)
    # ### end Alembic commands ###
