"""create ticket_templates table

Revision ID: ad78c31279d7
Revises: 6dbe323b9017
Create Date: 2025-09-15 10:21:42.713209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'ad78c31279d7'
down_revision: Union[str, Sequence[str], None] = '6dbe323b9017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'ticket_templates',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('background_url', sa.String(), nullable=False),
        sa.Column('fields', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_templates_id'), 'ticket_templates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_templates_id'), table_name='ticket_templates')
    op.drop_table('ticket_templates')
    # ### end Alembic commands ###
