"""link ticket_templates to stored_files

Revision ID: e0dfc92880db
Revises: c677f6aecfd9
Create Date: 2025-09-15 11:04:03.542374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e0dfc92880db'
down_revision: Union[str, Sequence[str], None] = 'c677f6aecfd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stored_files',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stored_files_id'), 'stored_files', ['id'], unique=False)
    op.add_column('ticket_templates', sa.Column('background_file_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_ticket_templates_background_file_id'), 'ticket_templates', ['background_file_id'], unique=False)
    op.create_foreign_key(None, 'ticket_templates', 'stored_files', ['background_file_id'], ['id'])
    op.drop_column('ticket_templates', 'background_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_templates', sa.Column('background_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ticket_templates', type_='foreignkey')
    op.drop_index(op.f('ix_ticket_templates_background_file_id'), table_name='ticket_templates')
    op.drop_column('ticket_templates', 'background_file_id')
    op.drop_index(op.f('ix_stored_files_id'), table_name='stored_files')
    op.drop_table('stored_files')
    # ### end Alembic commands ###
